# Generated by Django 4.2 on 2023-05-13 09:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0004_tag_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter_price',
            name='price',
            field=models.CharField(choices=[('<1000', '<1000'), ('1000 TO 10000', '1000 TO 10000'), ('10000 TO 20000', '10000 TO 20000'), ('20000 TO 30000', '20000 TO 30000'), ('30000 TO 40000', '30000 TO 40000'), ('40000 TO 50000', '40000 TO 50000'), ('50000 TO 60000', '50000 TO 60000'), ('60000 TO 70000', '60000 TO 70000'), ('70000 TO 80000', '70000 TO 80000'), ('80000 TO 90000', '80000 TO 90000'), ('90000 TO 100000', '90000 TO 100000'), ('100000 TO 200000', '100000 TO 200000'), ('200000 TO 300000', '200000 TO 300000'), ('300000 TO 400000', '300000 TO 400000'), ('400000 TO 500000', '400000 TO 500000'), ('>500000', '>500000')], max_length=60),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='information',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
